language: ru

pipeline:
  - name: SpacyNLP
    model: ru_core_news_lg
  - name: SpacyTokenizer
    intent_tokenization_flag: true
    intent_split_symbol: +
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 300
  - name: SpacyEntityExtractor
    dimensions: PERSON    
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 300
  - name: FallbackClassifier
    threshold: 0.65

policies:
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 10
     epochs: 300    
   - name: RulePolicy